site_name: FluidStack Infinity Documentation
theme: material
site_dir: docs
docs_dir: pages

nav:
    - 'index.md'
    - 'authentication.md'
    - 'plans.md'
    - 'Instant Deploys':
        - 'instant/deploy.md'
        - 'instant/list.md'
        - 'instant/view.md'
        - 'instant/delete.md'

extra:
    social:
    -   icon: fontawesome/solid/external-link-alt
        link: https://www.fluidstack.io
    
copyright: Copyright &copy; 2020 - 2021 FluidStack, Ltd

